const cds = [{imagen: '../assets/musica/returnOfTheDreamCanteen.png', codigo: 1, nombre: 'Return Of The Dream Canteen', precio: 2599},
                 {imagen: '../assets/musica/unlimitedLove.png', codigo: 2, nombre: 'Unlimited Love', precio: 3859},
                 {imagen: '../assets/musica/theGetaway.jpeg', codigo: 3, nombre: 'The Getaway', precio: 7851},
                 {imagen: '../assets/musica/imWithYou.jpeg', codigo: 4, nombre: 'Im With You', precio: 8599},
                 {imagen: '../assets/musica/stadiumArcadium.jpeg', codigo: 5, nombre: 'Stadium Arcadium', precio: 4894},
                 {imagen: '../assets/musica/greatestHits.jpg', codigo: 6, nombre: 'Greatest Hits', precio: 9748},
                 {imagen: '../assets/musica/byTheWay.jpeg', codigo: 7, nombre: 'By The Way', precio: 3281},
                 {imagen: '../assets/musica/californication.jpeg', codigo: 8, nombre: 'Californication', precio: 1938},
                 {imagen: '../assets/musica/oneHotMinute.jpeg', codigo: 9, nombre: 'One Hot Minute', precio: 3122},
                 {imagen: '../assets/musica/bloodSugarSexMagic.jpeg', codigo: 10, nombre: 'Blood Sugar Sex Magic', precio: 8745},
                 {imagen: '../assets/musica/mothersMilk.jpeg', codigo: 11, nombre: 'Mothers Milk', precio: 2599},
                 {imagen: '../assets/musica/theUpliftMofoPartyPlan.jpeg', codigo: 12, nombre: 1, tipo: 'The Uplift Mofo Party Plan', precio: 2599},
                 {imagen: '../assets/musica/freakyStyley.jpeg', codigo: 13, nombre: 'Freaky Styley.jpeg', precio: 2599},
                 {imagen: '../assets/musica/redHotChiliPeppers.jpeg', codigo: 14, nombre: 'Red Hot Chili Peppers', precio: 2599}]